name: PartyMayhem
version: '${project_version}'
main: com.butterycode.partymayhem.PartyMayhem
api-version: 1.19
authors: [ButterDebugger]
description: '${project_description}'
website: '${project_url}'

depend:
  - FastAsyncWorldEdit
  - Cuberry

commands:
  game:
    description: Manage minigames
    usage: /game <arguments>
    permission: partymayhem.admin
    aliases:
      - gamemayhem
  blueprint:
    description: Manage blueprints for minigames
    usage: /blueprint <arguments>
    permission: partymayhem.admin
    aliases:
      - blueprintmayhem

permissions:
  partymayhem.player:
    default: true
  partymayhem.admin:
    default: op