name: PartyMayhem
version: '${project.version}'
main: com.butterycode.partymayhem.PartyMayhem
api-version: 1.19
authors: [ButterDebugger]
description: '${project.description}'
website: '${project.url}'

depend:
  - FastAsyncWorldEdit
  - Cuberry

commands:
  game:
    description: Manage minigames
    usage: /game <arguments>
    permission: partymayhem.admin
    aliases:
      - gamemayhem

permissions:
  partymayhem.player:
    default: true
  partymayhem.admin:
    default: op